### ISSUE TITLE
Feature Request: Text Size Adjustment

### ISSUE THREAD

**Issue by naukri7707** [jonathanyeung/mark-sharp#17]
**Is your feature request related to a problem? Please describe.**
As a Chinese user, I find the current text size too small when writing Chinese markdown, especially in dark mode where it's quite straining to read clearly.

**Describe the solution you'd like**
Add an option to customize text size.

**Describe alternatives you've considered**
Considering consistency, it might be necessary to simultaneously enlarge content text, headings, and code. Perhaps a unified scaling option would be more straightforward and user-friendly.

By the way, is there a way to quickly switch between Mark Sharp dark/light themes without changing the VSCode theme? Sometimes I just want to preview how the content looks in the light theme.

**Comment by jonathanyeung** [comment]
Hi @naukri7707 - the two scenarios you mentioned (alter text size, change theme independently from VS Code theme) are not currently possible. The only way to alter text size right now is to change the scale of the entire VS Code UI. 

I was planning on making the styling of documents more customizable - I'll include your suggestions here as part of that effort.  Thank you for the feature request!

**Comment by jonathanyeung** [comment]
Hi @naukri7707 - I just released `1.5.0` which now has a setting and command `Mark Sharp: Editor Color Theme` that can let you preview in a default light mode (or dark mode).

I'm still working on the main part of this feature request - having a way to scale the text size.  I'll keep you updated when it's released.

**Comment by naukri7707** [comment]
Wow, thanks! This is exactly what I wanted.

**Comment by jonathanyeung** [comment]
Hi @naukri7707 - version `1.5.1` now has a setting and commands to scale the font size. Details can be found in the changelog:

> Adds a setting for adjusting the font size, mark-sharp.display.fontSize. This setting can also be adjusted through two convenience commands when an M# document is open, mark-sharp.increase-font-size and mark-sharp.decrease-font-size so that keyboard shorcuts can be added to quickly scale the text.

Let me know if you have any issues or questions.

**Comment by naukri7707** [comment]
Everything works great so far.
Thank you for your dedication. :D

As the issue has been resolved, I will close this issue.
