### ISSUE TITLE
Fenced code block with code specifier breaks the wysiwyg editor

### ISSUE THREAD

**Issue by simoneggler** [jonathanyeung/mark-sharp#20]
### Describe the bug.

The beginning of a fenced code block with a language specifier e.g. "mermaid" is not recognized by the wysiwyg editor. 

e.g. 
<img width="184" alt="image" src="https://github.com/user-attachments/assets/6764051d-4d82-430b-be6b-f69c5ffd69be">

looks like this: 
<img width="252" alt="image" src="https://github.com/user-attachments/assets/cd691766-d1d0-4b58-8bd3-d1c73dcb2e8d">

### Repro Steps

1. create o codeblock in source mode

<img width="121" alt="image" src="https://github.com/user-attachments/assets/d8a411fc-34a0-4f4b-9114-8559947f3eb0">

2. open the wysiwyg editor

### Version

2.142

### What platform are you seeing the problem on?

vscode.dev (web)

**Comment by jonathanyeung** [comment]
Hi @simoneggler - are there other contents in the markdown file? I'm not able to repro:

<img width="946" alt="image" src="https://github.com/user-attachments/assets/628cbb20-8147-470d-bd1f-c6db93147ab4">

**Comment by simoneggler** [comment]
indeed, i'm trying to find where i integrated the snippet that caused the error and i'm unable to do so. let's close this for now
