### ISSUE TITLE
Webview Error: Cannot read properties of undefined (reading 'getKey')

### ISSUE THREAD

**Issue by LLLbin** [jonathanyeung/mark-sharp#23]
### Describe the bug.

Cannot read properties of undefined (reading 'getKey')

The content of my markdown file is as follows:

![image](https://github.com/user-attachments/assets/ddcda51a-c737-4461-945a-58152bf05d35)

When I switch to Mark Sharp Editor Mode, an error message appears:

![image](https://github.com/user-attachments/assets/6e52a30c-9dad-4ad2-8abf-4fd5527740eb)

### Repro Steps

1. Create a md file.
2. Input: use `[text](link)` to create link
3. Use the command: Mark Sharp: Switch Editor Mode.
4. Bug happens.
![image](https://github.com/user-attachments/assets/a363c82f-51c2-40f3-aec6-516d60ed8d84)

### Version

1.4.1

### What platform are you seeing the problem on?

Windows

**Comment by jonathanyeung** [comment]
Thanks @LLLbin - I can repro this issue. I'll add it to my backlog.

**Comment by jonathanyeung** [comment]
This should be fixed in version `1.5.0`, which was released today.

**Comment by LLLbin** [comment]
Thank you for your help. It works now!
