### ISSUE TITLE
White Screen Flicker When Switching Markdown Files in Dark Mode

### ISSUE THREAD

**Issue by LLLbin** [jonathanyeung/mark-sharp#24]
Is your feature request related to a problem? Please describe.

- When switching between Markdown files in dark mode, a white screen flicker always occurs, which is very frustrating and significantly affects the reading and editing of Markdown files.

Describe the solution you'd like

- I hope that the file switching process can be smooth, without any white screen flicker, and that it can always stay in dark mode.

Describe alternatives you've considered

- The alternative solution I can think of is switching the VSCode theme to light mode. This would solve the white screen flicker problem, as the editor background is always white, so there wouldn't be any white screen flicker. However, I have always used VSCode in dark mode because I often use it at night for note-taking or coding. If I have to use VSCode in light mode at night, my eyes will feel very dry and uncomfortable. I hope this issue can be optimized.

Additional context

- Please see the attached video for details. The white screen flicker issue is severe when switching frequently.

https://github.com/user-attachments/assets/019e1bb4-d842-4947-a6b5-379934dd9f05

**Comment by jonathanyeung** [comment]
Hi @LLLbin - thanks so much for filing this issue.  This issue has been bothering me for a while too :) - I should have a fix for this in the next release.

**Comment by LLLbin** [comment]
Thanks for the quick response. I appreciate your efforts in addressing this issue. Look forward to the next release. 😊

**Comment by jonathanyeung** [comment]
This should be fixed in version `1.5.0`, which was just released.   Thanks for filing these issues! Let me know if you have additional feedback.

**Comment by LLLbin** [comment]
Thank you so much for your help! It works perfectly now.
