### ISSUE TITLE
Split view not rendering images (works in default MS MDown preview)

### ISSUE THREAD

**Issue by aioue** [jonathanyeung/mark-sharp#28]
### Describe the bug.

**Repro:**
VSCode Explorer open at `.`
Markdown file in `./path/markdown.md`
Image file in `./path/images/image.png`

**markdown.md contents:**
```raw
![foo image label](images/image.png)
```

**Result:**
<img width="230" alt="image" src="https://github.com/user-attachments/assets/226f5dba-fb69-446f-a859-459463a0532e">

**Result with in-built Markdown: Open Preview to Side**
Image renders.

### Repro Steps

1.
2.

### Version

1.5.0

### What platform are you seeing the problem on?

Mac OS

**Comment by jonathanyeung** [comment]
Hi @aioue - this should now be fixed in `1.5.1` - let me know if you're still having issues.

**Comment by aioue** [comment]
Working great in `1.5.1`, thanks!

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/908c5460-a8fe-46e7-a134-f01795fc8c21">
