### ISSUE TITLE
Unable to replace image URL by pasting

### ISSUE THREAD

**Issue by amks1** [jonathanyeung/mark-sharp#30]
### Describe the bug.

I'm getting this error in VSCode when I try to paste some URLs into the editor inside an image element. 
```
Minified Lexical error %2320, visit https://lexical.dev/docs/error%3Fcode=20 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
Example URL: https://d1pnnwteuly8z3.cloudfront.net/images/9f042b02-2819-4f40-90d9-2871fe998db7/ecec8337-d868-4f06-8e47-1c8ca8dba2a9.png

Screenshot:
![image](https://github.com/user-attachments/assets/1689c4c1-1d65-4b99-a9e4-5c7ab18b04e0)

### Repro Steps

1. Type in `![Image](https://d1pnnwteuly8z3.cloudfront.net/images/9f042b02-2819-4f40-90d9-2871fe998db7/ecec8337-d868-4f06-8e47-1c8ca8dba2a9.png)` to insert an image
2. When the image is previewed in the editor, click on it to show the URL below it
3. Paste another image URL to replace the current URL

### Version

1.5.0

### What platform are you seeing the problem on?

Windows

**Comment by jonathanyeung** [comment]
Thanks for filing this issue - I can repro.  Let me investigate.
