### ISSUE TITLE
Image is not rendering properly

### ISSUE THREAD

**Issue by thruthesky** [jonathanyeung/mark-sharp#36]
### Describe the bug.

When there is a space in the path of the image, it produces x-box.

See the video below;

https://github.com/user-attachments/assets/2b30c8e3-5057-4ffa-a75e-fd85c1580d15

### Repro Steps

1. Copy and paste the image into README. It will generate automatic name like `image (2).png`, `image (3).png`, ...
2. Put the image into TABLE. And there is error.

Fix:
When I remove the space in the file name the error disappears. For instance, renaming `image (2).png` to `image(2).png`.

### Version

1.5.1

### What platform are you seeing the problem on?

Mac OS

**Comment by thruthesky** [comment]
I found out a symtom;

If image.png and`image (1).png` exists, it will prompts the folder location two times; It has something to do with the automatical numbering.

**Comment by jonathanyeung** [comment]
Thanks for reporting the issue @thruthesky - I'll take a look.

**Comment by jonathanyeung** [comment]
Hi @thruthesky - images with spaces and angled brackets should render properly in tables in the latest update `1.6.0`. Let me know if you're still hitting issues.

**Comment by thruthesky** [comment]
It's working as expected.
Thank you
