### ISSUE TITLE
Image saving asks 3 times of choosing location

### ISSUE THREAD

**Issue by thruthesky** [jonathanyeung/mark-sharp#37]
### Describe the bug.

When I paste an image from clipboard, it is asking the location of image path for 3 times. See the video below;

https://github.com/user-attachments/assets/7efad310-609a-4f67-9745-e1e9c1cebee9

### Repro Steps

1. Copy and paste the image. And you will see it.

### Version

1.5.1

### What platform are you seeing the problem on?

Mac OS

**Comment by thruthesky** [comment]
Oops, I had choose 6 times to save image just now.

**Comment by thruthesky** [comment]
I found out a symtom;

If image.png andimage (1).png exists, it will prompts the folder location two times; It has something to do with the automatical numbering.

**Comment by jonathanyeung** [comment]
I'll investigate in conjunction with the other issue you opened, thanks!

**Comment by martinguenther** [comment]
I can confirm this behavior too. Pasting an image (image content, not file) from the clipboard, MS inserts it as image.png to the selected folder. When pasting the next image, I get to see the folder prompt twice.

**Comment by thruthesky** [comment]
> I can confirm this behavior too. Pasting an image (image content, not file) from the clipboard, MS inserts it as image.png to the selected folder. When pasting the next image, I get to see the folder prompt twice.

Hope this would be fixed soon. Image pasting is the reason I paid :)

**Comment by jonathanyeung** [comment]
I'll try to have a fix out for this soon, apologies for the issue.  In the meantime, if you downgrade to version `1.5.0` then I believe this multi-prompt problem shouldn't happen.

I'll post back once a fix is out.

**Comment by jonathanyeung** [comment]
Hi @thruthesky, @martinguenther - this issue should be fixed in version `1.6.0`, which has just been released. Let me know if you're still encountering issues.

There's still one issue where a 'No Folder Selected' notification popup will show up erroneously, but it can be ignored. I'll try to address this in the next update.

Thank you - appreciate the patience!

**Comment by thruthesky** [comment]
Yes, it's working as expected.
I will close the issue now.
Thank you.
